    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: source install_deps.sh
        working-directory: ./data_processing/
      - name: Download protobuf
        run: source download.sh
        working-directory: ./data_processing/
      - name: Run
        run: python3 usher_processing.py
        working-directory: ./data_processing/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: /tmp/distance_tree.nwk.gz
